spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 990812
#    url: jdbc:mysql://cdb-4tmpvvrh.gz.tencentcdb.com:10063/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.43.184:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /sell
